name: Tests (PHP)

on: [push]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run tests
        run: ./vendor/bin/phpunit --testsuite Unit